plugins {
    id("com.android.application") version "8.13.1" apply true
}

android {
    namespace 'com.android.deskclock'
    compileSdkVersion 36

    defaultConfig {
        minSdkVersion 31
        targetSdkVersion 34
    }

    sourceSets {
        main {
            res.srcDirs = ['res']
            java.srcDirs = ['src']
            assets.srcDirs = ['assets']
            manifest.srcFile 'AndroidManifest.xml'
        }
    }

    buildFeatures {
        buildConfig true
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    lint {
        lintConfig = file("lint.xml")
    }
}

dependencies {
    implementation 'io.github.dot166:j-Lib:104.0.7'
}

tasks.withType(JavaCompile) {
    options.compilerArgs << '-Xlint:unchecked'
//    options.deprecation = true
}
